event-app/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'pages#home'
  get 'pages/home'
  get 'pages/help'
  get 'pages/about'

  get    '/login',to: 'sessions#new'
  post   '/login',to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :events
  resources :users
  resources :invitations,only: [:create, :destroy]
    
  get    '/signup',to: 'users#new'
  post   '/signup',to: 'users#create'
  get '*path' => redirect('/') 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

event-app/app/models/event.rb
class Event < ApplicationRecord
  # scope
  scope :past, ->{ where("date < ?", Time.now) }
  scope :upcoming, ->{ where("date > ?", Time.now) }
  default_scope -> { order(created_at: :desc) }
  
  # Validations
  validates :title, presence: true, length: { maximum: 20 }
  validates :location, presence: true, length: { maximum: 10 }
  validates :description, presence: true, length: { maximum: 200 }
  validates :date, presence: true

  # Asscociation
  belongs_to :creator, class_name: "User"
  has_many :invitations, foreign_key: "attended_event_id"
  has_many :attendees, through: :invitations, source: :attendee   
end

event-app/app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

event-app/app/models/user.rb
class User < ApplicationRecord
  # validations
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  # Associations
  has_many :events, foreign_key: "creator_id"
  has_many :invitations, foreign_key: "attendee_id"
  has_many :attended_events, through: :invitations,source: :attended_event

  def feed
    Event.where("creator_id = :user_id", user_id: id)
  end

  def upcoming_events
    attended_events.where('date > ? ', Time.now )
  end

  def previous_events
    attended_events.where('date < ? ', Time.now )
  end

  def attend(event)
    invitations.create(attended_event_id: event.id)
  end

  def unattend(event)
    attended_events.delete(event)
  end
end

event-app/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :correct_user, only: :destroy

  def index
    @prev_events = Event.past
    @upcoming_events = Event.upcoming
  end

  def show
    @event = Event.find_by(id: params[:id])
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = "event created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'pages/home'
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Congratulations Event updated"
      redirect_to @event
    else
      render 'edit'
    end
  end

  def edit
    if @event = Event.find_by(id: params[:id])
    else
      flash[:danger] = "Event not found"
      redirect_to root_url
    end
  end

  def destroy
    @event.destroy
    flash[:success] = "Event deleted"
    redirect_to request.referrer || root_url
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :location, :date)
  end

  def correct_user
    @event = current_user.events.find_by(id: params[:id])
    redirect_to root_url if @event.nil?
  end
end

event-app/app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  
  def create
    @event = Event.find(params[:attended_event_id])
    current_user.attend(@event)
    respond_to do |format|
      format.html { render :controller => 'events', :action => 'index'  }
      format.js{render inline: "location.reload()"}
    end
  end

  def destroy
    @event = Invitation.find(params[:id]).attended_event
    current_user.unattend(@event)
    respond_to do |format|
      format.html { render :controller => 'events', :action => 'index'  }
      format.js {render inline: "location.reload()"}

    end
  end
end

event-app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    if logged_in?
      @event  = current_user.events.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
end

event-app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
  	  redirect_to user
    else
  	  flash[:danger] = "invalid email/password"
  	  redirect_to root_url
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

event-app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
     flash[:success] = 'Welcome to our app'
     redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

 private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

event-app/app/helpers/events_helper.rb
module EventsHelper
  def past?
    @event.date < Time.now
  end
end

event-app/app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id]=user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
  end
  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    current_user= nil
  end
end

event-app/app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end	
end

event-app/app/views/events/_attend.html.erb
  <%= form_for(event.invitations.build,remote: true) do |f| %>
    <div><%= hidden_field_tag :attended_event_id, event.id %></div>
    <%= f.submit "Attend", class: "btn btn-primary" %>
  <% end %>

event-app/app/views/events/_attendance_form.html.erb
  <div id="follow_form">
    <% if current_user.attended_events.include?(event) %>
      <%= render 'unattend',:event => event %>
    <% else %>
      <%= render 'attend', :event => event %>
    <% end %>
</div>

event-app/app/views/events/_event.html.erb
<li id="event-<%= event.id %>">
  <span class="user">
    <h3>Event by:<%= link_to event.creator.name, event.creator %></h3>
  </span>
  <span class="content"><h3>Title:<%= event.title %></h3><br>
    <h3>Description:<%= event.description %></h3><br>
    <h3> Location:<%= event.location %></h3><br>
    <h3> Date:<%= event.date.in_time_zone("Chennai").strftime("%d/%m/%Y %R ") %>
    </h3><br>
  </span> 
  <span class="timestamp">
    Posted <%= time_ago_in_words(event.created_at) %> ago.
      <% if current_user?(event.creator) %>
          <% if event.date > Time.now %>
            <%= link_to "delete", event, method: :delete,
                                       data: { confirm: "You sure?" } %>
            <%= link_to "edit", edit_event_path(event) %>
          <% else %>
          <% end %>
      <% end %>
  </span>
</li>

event-app/app/views/events/_unattend.html.erb
  <%= form_for(current_user.invitations.find_by(attended_event_id: event.id),
             html: { method: :delete },remote: true) do |f| %>
    <%= f.submit "Unattend", class: "btn" %>
  <% end %>

event-app/app/views/events/edit.html.erb
<div class="row">
  <%= render 'shared/event_form' %>
</div>

event-app/app/views/events/index.html.erb
<h1>Past Events</h1>
<% unless @prev_events.empty? %>
  <% @prev_events.each do |event| %>
    <li>
      <%= link_to "#{event.title}", event %>
    </li>
  <% end %>
  <% else %>
    <li>
      No past events.
    </li>
<% end %>

<h1>Upcoming Events</h1>
<% unless @upcoming_events.empty? %>
  <% @upcoming_events.each do |event| %>
    <li >
      <%= link_to "#{event.title}", event %>
      <%= render 'attendance_form', :event => event %>
    </li>
  <% end %>
  <% else %>
    <li>
      No Upcoming events.
   </li>
<% end %>

event-app/app/views/events/show.html.erb
 
 <%= render @event %>
 <% if @event.attendees.any? %>
   Attendee List:
   <% @event.attendees.each do |attendee| %>
     <h3> <li><%= attendee.name %></li></h3>
   <% end %>
<% else %>
  <li>no event attendees</li>
<% end %>

event-app/app/views/invitations/create.js.erb
$("#attendance_form").html("<%= escape_javascript(render('events/unattend')) %>");

event-app/app/views/invitations/destroy.js.erb
$("#attendance_form").html("<%= escape_javascript(render('events/attend')) %>");

event-app/app/views/pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/event_form' %>
      </section>
    </aside>

    <div class="col-md-8">
      <h3>Events</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Event App</h1>
    <h2>This is the home page for the Event App</h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %> 

event-app/app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>

  <div class="col-md-8">
    <% if current_user.upcoming_events.any? %>
      <h3> Your Upcoming Events </h3>
      <% current_user.upcoming_events.each do |upcoming_event| %>
          <%= render upcoming_event %>
      <% end %>
    <% end %> 

    <% if current_user.previous_events.any? %>
      <h3> Past Attended Events </h3>
      <%  current_user.previous_events.each do |past_event| %>
          <%= render past_event %>
      <% end %> 
    <% end %>
  </div>
</div>